name: Documentation

on:
  push:
    paths:
      - 'docs/**'
      - '**.md'
      - '**.org'

jobs:
  check-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check markdown files
      uses: DavidAnson/markdownlint-cli2-action@v11
      with:
        globs: '**/*.md'

    - name: Check for broken links
      uses: lycheeverse/lychee-action@v1
      with:
        args: --verbose --no-progress './**/*.md' './**/*.org'
        fail: false
