name: Formal Verification

on:
  push:
    paths:
      - 'specs/**'
  pull_request:
    paths:
      - 'specs/**'
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download TLA+ tools
      run: |
        mkdir -p tools/formal-methods
        wget -O tools/formal-methods/tla2tools.jar https://github.com/tlaplus/tlaplus/releases/download/v1.8.0/tla2tools.jar

    - name: Download Alloy
      run: |
        wget -O tools/formal-methods/alloy.jar https://github.com/AlloyTools/org.alloytools.alloy/releases/download/v6.1.0/alloy.jar

    - name: Run TLA+ verification
      run: |
        cd specs
        make check-tla || true

    - name: Run Alloy verification
      run: |
        cd specs
        make check-alloy || true
